version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ur-api
    volumes:
      - '.:/app'
    environment:
      MONGO_URL: ''
    command: /bin/sh -c "yarn start-watch"
    ports:
      - '4000:4000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - '27027:27017'

volumes:
  data-volume:
